---
title: "ClusterEDA"
author: "Ryan M. Allen"
date: "February 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data_libraries, cache=TRUE, message=FALSE, include=FALSE}
library(tidyverse)
library(data.table)
library(scales)
library(agricolae)
library(userfriendlyscience)
library(varhandle)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(rworldmap)  # getMap()
library(cowplot)
library(mice)
library(VIM)
library(caTools)
library(corrplot)
library(missForest)
library(factoextra)
library(cluster)
library(kableExtra)
library(clValid)
library(GGally)
library(NbClust)
library(patchwork)
library(fpc)
theme_set(theme_light())

kmeansdt <- read.csv("C:/Users/Ryan Allen/Documents/Regis/Classes/Practicum_I/Data/Data/kmeansData.csv")

hclusterdt <- read.csv("C:/Users/Ryan Allen/Documents/Regis/Classes/Practicum_I/Data/Data/hclustData.csv")
```

## EDA on the Clustered Data
```{r, cache=TRUE, message=FALSE}
# Based on the Scree plot, we are interested in the first 28 columns
imputed1 <- imputed1 %>% filter(longitude > -180)
trainData <- imputed1[,1:28]
sampleTrain <- trainData %>% sample_n(., 20000, replace = TRUE)
scaledTrain <- scale(sampleTrain)
km.out=kmeans(scaledTrain, 8, nstart = 20)

# Clusters Visualized
fviz_cluster(km.out, data = scaledTrain, geom = "point", pointsize = .5)

aggregate(kmeans, by=list(kmeansdt$Cluster), mean)
aggregate(hcluster, by=list(hclusterdt$Cluster), mean)

kmeans %>% select(region, weaptype1, attacktype1, Cluster) %>% 
   group_by(Cluster) %>% add_count()

# Distribution of Regions in the Clusters
kmeansRegions <- ggplot(kmeans, aes(x = Cluster, y = region, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red")

hclustRegions <- ggplot(hcluster, aes(x = Cluster, y = region, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red")

# Distribution of Weapon Types in the Clusters
kmeansWeapon <- ggplot(kmeans, aes(x = Cluster, y = weaptype1, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + theme(plot.title = element_text(size=15)) + labs(title = "Kmeans Weapon types")

hclustWeapon <- ggplot(hcluster, aes(x = Cluster, y = weaptype1, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red")

# Distribution of Attack Types in the Clusters
kmeansAttack <- ggplot(kmeans, aes(x = Cluster, y = attacktype1, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + labs(title = "Kmeans Attack Types")

hclustAttack <- ggplot(hcluster, aes(x = Cluster, y = attacktype1, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red")


kmeansRegions 
hclustRegions
kmeansAttack
hclustAttack
kmeansWeapon
hclustWeapon


kmeanslon <- ggplot(kmeansdt, aes(x = Cluster, y = longitude, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + labs(subtitle = "Kmeans Longitude")
kmeanslat <- ggplot(kmeansdt, aes(x = Cluster, y = latitude, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + labs(subtitle = "Kmeans Latitude")
hclustlat <- ggplot(hclustdt, aes(x = Cluster, y = latitude, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + labs(subtitle = "Hclust Latitude")
hclustlong <- ggplot(hclustdt, aes(x = Cluster, y = longitude, group = Cluster))+geom_boxplot() + geom_jitter(alpha = .1) + stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, fill = "red") + labs(subtitle = "Hclust Longitude")
kmeans %>% select(Cluster) %>% add_count(Cluster) %>% arrange(Cluster) %>% unique()


plotcluster(scaledTrain, km.out$cluster)
d <- dist(scaledTrain)
cluster.stats(d, km.out$cluster)

# Silhouette Coefficient
# Measure of how well an observation is clustered and finds the average dist between clusters, it is an internal measure.
view(pam.res$silinfo$widths)

# Silhouette information
silinfo <- pam.res$silinfo
names(silinfo)
# Silhouette widths of each observation
head(silinfo$widths[, 1:3], 10)
# Average silhouette width of each cluster
silinfo$clus.avg.widths
# The total average (mean of all individual silhouette widths)
silinfo$avg.width
# The size of each clusters
pam.res$size
# Silhouette width of observation
sil <- pam.res$silinfo$widths[, 1:3]
# Objects with negative silhouette
neg_sil_index <- which(sil[, 'sil_width'] < 0)
sil[neg_sil_index, , drop = FALSE]
#agreement between region and cluster
pam.res <- eclust(kmeans, "pam", k = 8, graph = FALSE)
table(kmeans$region, pam.res$cluster)
clust_stats <- cluster.stats(d = dist(kmeansdt), 
                             kmeansdt$region, pam.res$cluster)
clust_stats$corrected.rand
clust_statsw <- cluster.stats(d = dist(kmeansdt), 
                             kmeansdt$weaptype1, pam.res$cluster)
clust_statsw$corrected.rand
clust_statsa <- cluster.stats(d = dist(kmeansdt), 
                             kmeansdt$attacktype1, pam.res$cluster)
clust_statsa$corrected.rand

```

```{r}
# Criteria for a terrorist attack

kmeans %>% 
    select(Cluster, crit1, crit2, crit3) %>%
    group_by(Cluster) %>%
    mutate(c1count = sum(crit1)) %>% 
    mutate(c2count= sum(crit2)) %>% 
    mutate(c3count = sum(crit3)) %>% 
    select(Cluster, c1count, c2count, c3count) %>% 
    unique() %>% 
    arrange(Cluster)

# By regioin which criteria was most popular?
# Crit 1 =  POLITICAL, ECONOMIC, RELIGIOUS, OR SOCIAL GOAL 
# Crit 2 = INTENTION TO COERCE, INTIMIDATE OR PUBLICIZE TO LARGER AUDIENCE(S)
# Crit 3 = OUTSIDE INTERNATIONAL HUMANITARIAN LAW 
kmeans %>% 
    select(Cluster, crit1, crit2, crit3) %>%
    group_by(Cluster) %>%
    mutate(c1count = sum(crit1)) %>% 
    mutate(c2count= sum(crit2)) %>% 
    mutate(c3count = sum(crit3)) %>% 
    select(Cluster, c1count, c2count, c3count) %>% 
    group_by(Cluster) %>% 
    mutate(clustertotal = c1count + c2count + c3count) %>% 
    mutate(c1percent = c1count/clustertotal) %>% 
    mutate(c2percent = c2count/clustertotal) %>% 
    mutate(c3percent = c3count/clustertotal) %>% 
    select(Cluster, c1percent, c2percent, c3percent, clustertotal) %>% 
    unique() %>% 
    arrange(Cluster)



```


```{r}
centers <- as.data.frame(km.out$centers)
names(centers) <- paste("Cluster", 1:8)
centers$Symbol <- row.names(centers)
centers <- gather(centers, "Cluster", "Mean", -Symbol)
centers$Color = centers$Mean > 0
ggplot(centers, aes(x = Symbol, y = Mean, fill = Color)) +
    geom_bar(stat = "identity", position = "identity", width = .75) +
    facet_grid(Cluster ~ . , scales = 'free_y')


```

